trigger:
- main
stages:
- stage: Build
  jobs:
  - job: BuildJob
    pool:
      name: build-env-servers
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'package'
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/target/'
        Contents: 'netflix.war'
        TargetFolder: '/home/praveen/mypipelinework/2/a/'

    - script: |
        echo "Artifact Staging Directory: $BUILD_ARTIFACTSTAGINGDIRECTORY"
      displayName: 'Print Artifact Staging Directory'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
